#! /bin/bash
if [ -f /etc/init.d/sshd ]; then
	if [ "$NUT_ENVIRONMENT" = "home" ]; then
		echo "Entered environment $NUT_ENVIRONMENT"
		/etc/init.d/sshd status
		if [ $? = 0 ]; then
			/etc/init.d/sshd reload
		else
			/etc/init.d/sshd start
		fi
	else #leaving
		/etc/init.d/sshd stop
	fi
fi
