#! /bin/bash

/etc/init.d/avahi-daemon status &> /dev/null
if [ $? = 1 ]; then
	if [ "$NUT_STATUS" = zeroconf ]; then
		logger -p daemon.info -t "nuts:start_avahi" "Starting avahi-daemon"
		/etc/init.d/avahi-daemon start
	fi
fi
