#! /bin/bash
if [ -f /etc/init.d/sshd ]; then
	if [ "$NUT_ENVIRONMENT" = home ]; then
		logger -p daemon.info -t "nuts:start_sshd" "Entered environment home"
		/etc/init.d/sshd status
		if [ $? = 0 ]; then
			/etc/init.d/sshd reload
		else
			/etc/init.d/sshd start
		fi
	else #leaving
		/etc/init.d/sshd stop
	fi
fi
