.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH CNUT 1 "December 18, 2007"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
cnut \- command line client for the Network UTility Server (nuts)
.SH SYNOPSIS
.B cnut
.SH DESCRIPTION
command line client for the Network UTility Server (nuts).
.SH COMMAND LINE OPTIONS
.TP
\fB--list (-l)\fR
Lists available devices, environments or interfaces
.TP
\fB--device (-D) <devicename>\fR
Choose device
.TP
\fB--environment (-E) <environment name>\fR
Choose environment in given device
.TP
\fB--environment (-E) <environment index>\fR
Choose environment in given device
.TP
\fB--interface (-I) <interface index>\fR
Choose interface in given environment
.TP
\fB--enable (-1)\fR
Enables given device
.TP
\fB--disable (-0)\fR
Disables given device
.TP
\fB--type (-t)\fR
returns type of given device or interface
.TP
\fB--state (-s)\fR
returns state of given device or environment or interface
.TP
\fB--activeEnvironment (-a)\fR
returns active Environment of given device
.TP
\fB--setEnvironment (-S) <environment name>\fR
Activates the environment on the given device
.TP
\fB--properties (-p)\fR
Returns interface properties (one ip per line): ip,netmask,gateway,dns-servers
.TP
\fB--setEnvironment (-S) <index>\fR
Activates the environment on the given device
.TP
\fB--selectable\fR
returns if an environment is selected,selectable or not selectable
.TP
.SH EXAMPLES
cnut --device eth0 --enable Enables device eth0
cnut --device eth0 --state Shows state of device eth0
cnut --device eth0 --environment "home" --state Shows state of environment home of device eth0
.SH SEE ALSO
.BR nuts (1).
.SH AUTHOR
cnut was written by Daniel Bahrdt <d.bahrdt@gmx.de>, Oliver Gro\[ss] <neokensuke@freenet.de> and Stefan B\[:u]hler <stbuehler@web.de>.
