.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH NUTS 8 "August 31, 2007"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
nuts \- Network UTility Server
.SH SYNOPSIS
.B nuts
.SH DESCRIPTION
Network UTility Server (nuts)
.SH SEE ALSO
.BR qnut (1).
.SH AUTHOR
nuts was written by Daniel Bahrdt <d.bahrdt@gmx.de>, Oliver Gro\[ss] <neokensuke@freenet.de> and Stefan B\[:u]hler <stbuehler@web.de>.
