set(CMAKE_CXX11_FLAGS -std=c++11 CACHE STRING "flags to enable C++11")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${CMAKE_CXX11_FLAGS}")

set(CMAKE_C99_FLAGS -std=c99 CACHE STRING "flags to enable C99")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${CMAKE_C99_FLAGS}")

mark_as_advanced(FORCE CMAKE_CXX11_FLAGS CMAKE_C99_FLAGS)
