# require at least 3.0; 3.1 knows C_STANDARD / CXX_STANDARD
if((${CMAKE_MAJOR_VERSION} GREATER 3) OR (${CMAKE_MINOR_VERSION} GREATER 0))
	set(CMAKE_CXX_STANDARD 11)
	set(CMAKE_CXX_STANDARD_REQUIRED ON)

	set(CMAKE_C_STANDARD 99)
	set(CMAKE_C_STANDARD_REQUIRED ON)
else()
	set(CMAKE_CXX11_FLAGS -std=c++11 CACHE STRING "flags to enable C++11")
	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${CMAKE_CXX11_FLAGS}")

	set(CMAKE_C99_FLAGS -std=c99 CACHE STRING "flags to enable C99")
	set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${CMAKE_C99_FLAGS}")

	mark_as_advanced(FORCE CMAKE_CXX11_FLAGS CMAKE_C99_FLAGS)
endif()
